### ISSUE TITLE
[SETUP] Update Versions

### ISSUE THREAD

**Issue by belkmouf** [lux-org/lux#164]
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning: 
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.

Please report this issue on Github: https://github.com/lux-org/lux/issues 
  return method()

**Comment by dorisjlee** [comment]
Hi @belkmouf, Thank you for your interest in Lux. We just had an updated release with some bug fixes and a more debuggable printout of the error message. Could you try installing this using the following command?
```
pip install lux-api==0.2.1
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Note that you may have to restart your jupyter notebook after doing this so that the change is reflected.
After this, if you can send a screenshot of the error and the operations that led up to it, it would be very helpful for debugging.
