### ISSUE TITLE
[SETUP] conda support (ModuleNotFoundError)

### ISSUE THREAD

**Issue by usapkota** [lux-org/lux#177]
After installing lux-api [pip install lux-api], while trying to to install nbextension [jupyter nbextension install --py luxwidget] you get this module not found error. 

[using python 3.7.3 on conda]

**Comment by dorisjlee** [comment]
Hi @usapkota, This is possibly happening because your pip install is installing in a different director as what your jupyter accesses, see [this issue](https://stackoverflow.com/questions/52096590/no-module-found-error-for-every-conda-package-in-anaconda-jupyter-notebook). Could you check if the lux-api and luxwidget is being installed on the same environment as the one triggered by your jupyter command?

**Comment by CWen001** [comment]
Is it possible to publish lux in conda-forge?

**Comment by dorisjlee** [comment]
Hi @CWen001, Thanks for the suggestion! We can look into putting lux on `conda-forge` although we'll have to do a bit more testing and setup on our end to see if it fixes this issue. Stay tuned for updates when this becomes available!

**Comment by cjachekang** [comment]
Hi @CWen001 , @usapkota , Lux is officially on conda-forge! If you would like to try install via conda, you can use the command `conda install -c conda-forge lux-api`. If any issues persist, let us know and feel free to reopen this issue!

**Comment by CWen001** [comment]
Thanks for implementing! I have already enjoyed using lux for a while.
