### ISSUE TITLE
[Question] Large dataframe warnings

### ISSUE THREAD

**Issue by beneslami** [lux-org/lux#340]
Hello. Thank you so much for creating and maintaining lux. I got below warning
![Screen Shot 2021-04-03 at 9 37 30 PM](https://user-images.githubusercontent.com/10661404/113489524-12371500-94c5-11eb-96ea-d157dd29ed91.png)

Is it a serious thing? because I have a large data set and I need each item

**Comment by dorisjlee** [comment]
Hi @beneslami, Thanks for your interest in Lux and question! Lux performs some default optimizations to make the recommendations run faster. The first warning that you are seeing is stating that we are sampling only 30k rows since the dataframe is large. The second warning says that the visualizations are plotted as heatmap, this is again because the dataframe is large so plotting scatterplots would be fairly slow. If you want to turn either the sampling or the heatmap off, you can do something like: 
```python
lux.config.sampling = False
or 
lux.config.heatmap = False
```
Please check out [this page](https://lux-api.readthedocs.io/en/latest/source/reference/config.html#change-the-sampling-parameters) for more details. Let us know if that solves the issue for you!

**Comment by dorisjlee** [comment]
Closing this for now, please let us know if you have additional questions or issues!
