### ISSUE TITLE
[BUG] TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by muammar** [lux-org/lux#407]
**Describe the bug**

When importing `lux` and trying to create a `.lineplot()` with `seaborn` during a `for` loop, I get the `TypeError` shown on the title of this bug report. 

**To Reproduce**

I am uploading a notebook that can reproduce this error. You will also find a pickle file with a DataFrame that gives me the error in the zip file:

```
  % md5 lux_error_reproducibility.zip                                                                                                   
MD5 (lux_error_reproducibility.zip) = e8d110587d153e58df3f1e2ec771fd43
```

**Expected behavior**

Having the line plots created without any issue. 

**Screenshots**

Error when `import lux` is activated. 

![image](https://user-images.githubusercontent.com/954209/128774779-71404886-2129-4f30-b8c7-3a47937106bc.png)

Commenting `import lux`, killing the kernel, and re-running the notebook: 

![image](https://user-images.githubusercontent.com/954209/128775150-37bf611f-2a97-4625-8cdc-f7b1c5ee78c4.png)
[lux_error_reproducibility.zip](https://github.com/lux-org/lux/files/6957506/lux_error_reproducibility.zip)

**Comment by dorisjlee** [comment]
Hi @muammar, 

Thank you for reporting this issue and the detailed steps to reproduce the errors! It looks like when lux is imported, the groupby called by seaborn leads to some issues on the LuxDataFrame. I was not exactly able to reproduce this issue since I had trouble opening the attached `molfeat.pkl` file, but testing this on a synthetic dataset of similar nature, I could not see the same error. 
![Screen Shot 2021-08-13 at 10 56 51 AM](https://user-images.githubusercontent.com/5554675/129400066-3e173877-eb99-4048-99e6-1c256f6473f3.png)

Could you let me know which version of Lux you are using? (i.e., `print(lux.__version__)`)
You could also try to see if upgrading to the latest version of lux-api might fix the problem: 
```
pip install --upgrade lux-api
```
And optionally: 
```
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```

Please let me know if this issue is resolved after upgrading to the latest version? Thanks again!

**Comment by muammar** [comment]
> Hi @muammar,
> 
> Thank you for reporting this issue and the detailed steps to reproduce the errors! It looks like when lux is imported, the groupby called by seaborn leads to some issues on the LuxDataFrame. I was not exactly able to reproduce this issue since I had trouble opening the attached `molfeat.pkl` file, but testing this on a synthetic dataset of similar nature, I could not see the same error.


Sorry, it took me long to reply. I am uploading a `CSV` file with the same content as the pickle file to reproduce the issue:

[molfeat.csv](https://github.com/lux-org/lux/files/7137105/molfeat.csv)


> Could you let me know which version of Lux you are using? (i.e., `print(lux.__version__)`)

```
print(lux.__version__)
0.3.0
```

> You could also try to see if upgrading to the latest version of lux-api might fix the problem:
> 
> ```
> pip install --upgrade lux-api
> ```
> 
> And optionally:
> 
> ```
> jupyter nbextension install --py luxwidget
> jupyter nbextension enable --py luxwidget
> ```
> 
> Please let me know if this issue is resolved after upgrading to the latest version? Thanks again!

I upgraded to `0.3.2`, and the issue is not there anymore! Thanks! 

I will proceed to close the report.

**Comment by dorisjlee** [comment]
That sounds great, thanks for letting us know @muammar!
