### ISSUE TITLE
[BUG] Slack Link

### ISSUE THREAD

**Issue by flight505** [lux-org/lux#410]
**Describe the bug**

Getting access to the Slack channel fast enough. The Slack Link is: https://communityinviter.com/apps/lux-project/lux but the Beta communityinviter still refuses people that are not members of that slack group. In which case it confuses the user and you don't know if admin is receiving requests. 
Why not just open lux-project.slack.com? 

In any case please approve my mail

**Comment by dorisjlee** [comment]
Hi @flight505, 
Thanks for reporting this issue! It seems like the Community Inviter link expired, I just refreshed this, so this link should work: https://communityinviter.com/apps/lux-project/lux

Otherwise, you can use this [direct invite link](https://join.slack.com/t/lux-project/shared_invite/zt-umycf1sy-2fTaRgIvwj3bfkEtb~ZnhQ). To your question, the reason for using CommunityInviter is because Slack invite links expire by default after 30 days. Hope that solves the issue for you!
