### ISSUE TITLE
Remove excessive computation of metadata in __setitem__

### ISSUE THREAD

**Issue by westernguy2** [lux-org/lux#81]
Currently, `__setitem__` computes the metadata when called

```
def __setitem__(self, key, value):
	super(LuxDataFrame, self).__setitem__(key, value)
	self.compute_stats()
	self.compute_dataset_metadata()
```

However, when `_repr_html_` is called, the metadata is computed many times more than is necessary.

Removing this metadata computation causes Lux tests to fail.

**Comment by dorisjlee** [comment]
Removed unnecessary metadata computation in `__setitem__`, addressed test errors by fixing cardinality and unique value access in tests.

Performance improvement with Census dataset: 
```
$ python -m pytest -s tests/test_performance.py

# Before fix
1st display Performance: 3.0770 seconds
2nd display Performance: 0.0316 seconds

# After fix
1st display Performance: 2.6792 seconds
2nd display Performance: 0.0300 seconds
```
Total speedup of about 0.4 seconds

**Comment by dorisjlee** [comment]
Update: We switched to an expiration strategy for `__setitem__` so that the metadata and recommendations are forced to recompute when the users makes changes to the dataframe via `df["attribute"] = ...`. For example, `df['date'] = pd.to_datetime(df['date'],format="%Y-%m-%d")` should trigger recomputation of recs and vis to with the new temporal data types. The performance is unaffected by this change, we still get a total speedup of about 0.4 seconds even with this change.
